package ajj;
// Generated 7 Oct, 2018 12:11:58 PM by Hibernate Tools 4.3.1



/**
 * Hb generated by hbm2java
 */
public class Hb  implements java.io.Serializable {


     private int id;
     private String name;
     private String type;

    public Hb() {
    }

    public Hb(int id, String name, String type) {
       this.id = id;
       this.name = name;
       this.type=type;
    }

    Hb(String name) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
}


